#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
$host = gethostname();
$env = ($host && $host == 'kubrey') ? 'dev' : 'production';

defined('YII_DEBUG') or define('YII_DEBUG', $env == 'dev' ? true : false);
defined('YII_ENV') or define('YII_ENV', $env);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
